name: Update Conference Data

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行
  workflow_dispatch:      # 允许手动触发

jobs:
  update-conferences:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 添加写入权限
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0   # 获取完整历史记录
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml
    
    - name: Run scraper
      run: |
        mkdir -p public/data
        python scripts/scraper.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add public/data/conferences.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update conference data" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Deploy to GitHub Pages
      run: |
        git checkout gh-pages
        git merge main -m "Merge main into gh-pages"
        git push origin gh-pages 